// Copyright 2018-2022 Nick Brassel (@tzarc)
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

// RGB configuration
#define WS2812_PWM_DRIVER PWMD5
#define WS2812_PWM_CHANNEL 4
#define WS2812_PWM_PAL_MODE 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM0
#define WS2812_DMA_CHANNEL 6

// WEAR_LEVELING_DRIVER = embedded_flash
// #define BACKING_STORE_WRITE_SIZE 4
// WEAR_LEVELING_DRIVER = legacy
// #define BACKING_STORE_WRITE_SIZE 2

// 405XE
// #define WEAR_LEVELING_LEGACY_EMULATION_PAGE_SIZE 16384
// #define WEAR_LEVELING_BACKING_SIZE (16384)
// #define WEAR_LEVELING_LOGICAL_SIZE ((WEAR_LEVELING_BACKING_SIZE) / 2)
// #define WEAR_LEVELING_LEGACY_EMULATION_PAGE_COUNT 1
// #define WEAR_LEVELING_LEGACY_EMULATION_BASE_PAGE_ADDRESS (WEAR_LEVELING_LEGACY_EMULATION_FLASH_BASE + (2 * (WEAR_LEVELING_LEGACY_EMULATION_PAGE_SIZE))) // +32k
